title: Keisuu's Config
subtitle: Config and other stuff 
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Config Page :D

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about


# Edit these details

author_logo: AtagoWaifuRaceQueen.jpg
author: Arthur "Keisuu"
author_bio: Hi, I'm Keisuu ! 20 years old, big FPS Fan, especially CS:GO !
author_email: 
author_location: France
author_website_url: "https://steamcommunity.com/id/keisuuthabeast/"
typewrite-text: If u got any question, don't hesitate !



# social links
twitter_username: KeisuuCSGO
github_username:  Keisuuu
facebook_username: Arthur
instagram_username: arthur_keisuu


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )



# formspree (contact form)
formspree_email: j

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true


# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'




# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build

